//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EN.Telegram.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EN.Telegram.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the receiver of message.
        /// </summary>
        public static string SendFile_CHATID_Description {
            get {
                return ResourceManager.GetString("SendFile_CHATID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT ID.
        /// </summary>
        public static string SendFile_CHATID_DisplayName {
            get {
                return ResourceManager.GetString("SendFile_CHATID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a file to a specified usetr.
        /// </summary>
        public static string SendFile_Description {
            get {
                return ResourceManager.GetString("SendFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send File.
        /// </summary>
        public static string SendFile_DisplayName {
            get {
                return ResourceManager.GetString("SendFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local path of the file to be sent.
        /// </summary>
        public static string SendFile_FilePath_Description {
            get {
                return ResourceManager.GetString("SendFile_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string SendFile_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("SendFile_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code of the reuqest.
        /// </summary>
        public static string SendFile_STATUSCODE_Description {
            get {
                return ResourceManager.GetString("SendFile_STATUSCODE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS CODE.
        /// </summary>
        public static string SendFile_STATUSCODE_DisplayName {
            get {
                return ResourceManager.GetString("SendFile_STATUSCODE_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the receiver of message.
        /// </summary>
        public static string SendMessage_CHATID_Description {
            get {
                return ResourceManager.GetString("SendMessage_CHATID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT ID.
        /// </summary>
        public static string SendMessage_CHATID_DisplayName {
            get {
                return ResourceManager.GetString("SendMessage_CHATID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message to a specific user.
        /// </summary>
        public static string SendMessage_Description {
            get {
                return ResourceManager.GetString("SendMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage_DisplayName {
            get {
                return ResourceManager.GetString("SendMessage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text message to be sent.
        /// </summary>
        public static string SendMessage_MESSAGE_Description {
            get {
                return ResourceManager.GetString("SendMessage_MESSAGE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGE.
        /// </summary>
        public static string SendMessage_MESSAGE_DisplayName {
            get {
                return ResourceManager.GetString("SendMessage_MESSAGE_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code of the reuqest.
        /// </summary>
        public static string SendMessage_STATUSCODE_Description {
            get {
                return ResourceManager.GetString("SendMessage_STATUSCODE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS CODE.
        /// </summary>
        public static string SendMessage_STATUSCODE_DisplayName {
            get {
                return ResourceManager.GetString("SendMessage_STATUSCODE_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the receiver of message.
        /// </summary>
        public static string SendPhoto_CHATID_Description {
            get {
                return ResourceManager.GetString("SendPhoto_CHATID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT ID.
        /// </summary>
        public static string SendPhoto_CHATID_DisplayName {
            get {
                return ResourceManager.GetString("SendPhoto_CHATID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends an image to a specific user.
        /// </summary>
        public static string SendPhoto_Description {
            get {
                return ResourceManager.GetString("SendPhoto_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Photo.
        /// </summary>
        public static string SendPhoto_DisplayName {
            get {
                return ResourceManager.GetString("SendPhoto_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local path of the image to be sent.
        /// </summary>
        public static string SendPhoto_IMAGEPATH_Description {
            get {
                return ResourceManager.GetString("SendPhoto_IMAGEPATH_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE PATH.
        /// </summary>
        public static string SendPhoto_IMAGEPATH_DisplayName {
            get {
                return ResourceManager.GetString("SendPhoto_IMAGEPATH_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code of the reuqest.
        /// </summary>
        public static string SendPhoto_STATUSCODE_Description {
            get {
                return ResourceManager.GetString("SendPhoto_STATUSCODE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS CODE.
        /// </summary>
        public static string SendPhoto_STATUSCODE_DisplayName {
            get {
                return ResourceManager.GetString("SendPhoto_STATUSCODE_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token of the bot.
        /// </summary>
        public static string TelegramScope_APITOKEN_Description {
            get {
                return ResourceManager.GetString("TelegramScope_APITOKEN_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API TOKEN.
        /// </summary>
        public static string TelegramScope_APITOKEN_DisplayName {
            get {
                return ResourceManager.GetString("TelegramScope_APITOKEN_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope to include all telegram activities.
        /// </summary>
        public static string TelegramScope_Description {
            get {
                return ResourceManager.GetString("TelegramScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Scope.
        /// </summary>
        public static string TelegramScope_DisplayName {
            get {
                return ResourceManager.GetString("TelegramScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
